### PR TITLE
Colorize devtools output

### PR DESCRIPTION
**Pull request by mazurov**
Convert console codes to html tags.

grunt-devtools-colorized png

### CODE REVIEW

**Comment by vladikoff** [comment]
This is so awesome! Thanks for the PR and taking the time to figure out how to colour these things. 
I'm cleaning up the current dev version to use LESS, so I might not be able to do an auto merge. However, I'll make sure this lands in the next version.

**Comment by mazurov** [comment]
Welcome! :smile: You have created  a good tool for web developers. Thanks! :thumbsup:

**Comment by vvakame** [comment]
:+1:

**Comment by vladikoff** [comment]
Support for this has been merged into https://github.com/vladikoff/grunt-devtools/tree/dev
This feature will be live in `0.2.0`!

**Pull request closed without merging**
